### ISSUE TITLE
Time is not updating in header

### ISSUE THREAD

**Issue by vikrammahto** [vikrammahto/tototimer#2]
[Desktop mode] time is not updating.

**Comment by alvarotorrestx** [comment]
Hi there, I wanted to help with this issue but I'm unsure on what you mean by it not updating? It is working properly on desktop for me:
![image](https://github.com/vikrammahto/tototimer/assets/79110517/8b458129-97b2-468c-900d-99483fea4250)

But in a mobile view, it is possibly being cut off or not being shown at all:
![image](https://github.com/vikrammahto/tototimer/assets/79110517/fd5ba941-6458-4dba-9fad-0123aba9fa93)


Would you like me to try and assist with this or could you provide clarity, please?

Thanks!

**Comment by vikrammahto** [comment]
Hey @alvarotorrestx sorry for non-descriptive issue. 

The issue is: In Desktop mode, time is updated on page load. Suppose it's 09:27AM...and you stay at the same page, time doesn't changes. You can use setInterval along with useEffect hook to fix this. 

In mobile, time is shown in notification are by OS itself, so I have made time hidden for mobile device. 

Hope you go the issue. Let me know if you need any help.
